In [1]:

library(lubridate) #esta sí
library(dplyr)
load(file = 'cervezasImputacion.rdata')
load( file = 'catalogoCervezas.rdata') #catalogo con los detalles SOLO de las cervezas
cervezas %>% filter(montomargen>0)-> cervezas.ganancia
cervezas.ganancia %>% group_by(id_producto, id_fecha) %>%
    summarise(cantidad=sum(cantidad), monto=sum(monto),
              montomargen=sum(montomargen))-> cervezas.ganancia.dia
remove(cervezas)
gc()
Sys.sleep(10)
library(dtwclust)
series <- sort(unique(catalogo.cervezas$PRODUCTO_KEY ))
multi.series <- list()
for (i in 1:length(series))
{
    d <- subset(cervezas.ganancia.dia, id_producto==series[i])
    d$loc <- NULL
    d <- merge(d, catalogo.cervezas[, c( "PRODUCTO_KEY", "PRODUCTO_DES"  )],
               all.x=TRUE, by.x='id_producto', by.y='PRODUCTO_KEY' )
    d$id_producto <- NULL
    d$PRODUCTO_DES <- NULL
    #multi.series[[i]] <- as.matrix(d[, c("cantidad", "monto", "montomargen")])
    multi.series[[i]] <- as.matrix(d[, c("montomargen")])
}
d <- data.frame(id=catalogo.cervezas$PRODUCTO_KEY, descripcion=catalogo.cervezas$PRODUCTO_DES,
                subsegmento =catalogo.cervezas$SUBSEGMENTO_DES)
d <- unique(d)
d <- d[order(d$id), ]
names(multi.series) <- d$descripcion
#interactive_clustering(multi.series)
#save(clusterDia, file='clusterDia.rdata')
load('clusterDia.rdata')
d$cluster <- clusterDia@cluster
d[order(d$cluster, d$id),]
#jerarquico, 3 clusters, distancia sbd type:series

Attaching package: 'lubridate'

The following object is masked from 'package:base':

    date


Attaching package: 'dplyr'

The following objects are masked from 'package:lubridate':

    intersect, setdiff, union

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

       used      (Mb)  gc trigger (Mb)   max used  (Mb)
Ncells    662487  35.4   1093262    58.4   1093262   58.4
Vcells 115979179 884.9 318542126  2430.3 274537249 2094.6

Warning message:
"package 'dtwclust' was built under R version 3.5.2"Loading required package: proxy
Warning message:
"package 'proxy' was built under R version 3.5.2"
Attaching package: 'proxy'

The following objects are masked from 'package:stats':

    as.dist, dist

The following object is masked from 'package:base':

    as.matrix

Loading required package: dtw
Warning message:
"package 'dtw' was built under R version 3.5.2"Loaded dtw v1.20-1. See ?dtw for help, citation("dtw") for use in publication.

dtwclust:
Setting random number generator to L'Ecuyer-CMRG (see RNGkind()).
To read the included vignettes type: browseVignettes("dtwclust").
See news(package = "dtwclust") after package updates.

   id       descripcion          subsegmento        cluster
20 10009851 COORS LIGHT 355ML    Individual Lata NR 1
6  10017023 TECATE LIGHT 473ML   Individual Lata NR 1
4  10018949 COORSLIGHT 12P 355ML 12 pack Lata NR    1
13 10021678 TECATE L 18P 355ML   18 pack Lata NR    1
22 10023164 TECATE LIGHT 24OZ    Individual Lata NR 1
24 10023418 TECATE 24OZ          Individual Lata NR 1
8  10048586 TECATE L 24P 355ML   24 pack Lata NR    1
18 10051918 HEINEKEN LATA 355ML  Individual Lata NR 1
16 10061130 INDIO LATA 473ML     Individual Lata NR 1
1  10071306 TECATETITANIUM 355ML 6 Pack             1
7  23001    TECATE 355ML         Individual Lata NR 1
11 23196    XX LAGER 355ML       Individual Lata NR 1
23 38361461 SOL CLAMATO 473ML    Individual Lata NR 1
30 52255    TECATE L 12P 355ML   12 pack Lata NR    1
19 53004    TECATE 12P 355ML     12 pack Lata NR    1
2  54144726 TITANIUM 12 PACK     12 pack Lata NR    1
9  64532    TECATE 18P 355ML     18 pack Lata NR    1
31 69197    TECATE 473ML         Individual Lata NR 1
25 10017307 CB LIGHT 355ML       Individual Lata NR 2
10 10052957 SOL CLAM LATA 355ML  Individual Lata NR 2
12 13858510 XX RADLER LATA 355ML Individual Lata NR 2
29 23540    SOL 355ML            Individual Lata NR 2
15 46366    TECATE LIGHT 355ML   Individual Lata NR 2
26 54146584 AMSTEL LATA 355 ML   Individual Lata NR 2
33 54146586 AMSTEL LATA 12 PACK  12 pack Lata NR    2
27 54149641 CERVEZHEINEKEN 473ML Individual Lata NR 2
34 54150830 XX L 12 PACK 355 ML  12 pack Lata NR    2
3  54150844 INDIO 12 PACK 355 ML 12 pack Lata NR    2
5  54157852 SOL MICHELADA 473ML  Individual Lata NR 2
28 10034321 SOL CERO LYS 355ML   Individual Lata NR 3
17 10047930 COORS L 18P 355ML    18 pack Lata NR    3
21 10048582 SOL CERO LATA 355ML  Individual Lata NR 3
14 10057271 TECATE L 15P 355ML   15 Pack Lata NR    3
32 10074735 COORSLIGHT 473 ML    Individual Lata NR 3